In [3]:
import pandas as pd
StuPerfDF= pd.read_csv('study_performance.csv')
StuPerfDF = StuPerfDF[['gender','lunch','test_preparation_course','math_score','reading_score','writing_score']]
print(StuPerfDF)

     gender         lunch test_preparation_course  math_score  reading_score  \
0    female      standard                    none          72             72
1    female      standard               completed          69             90
2    female      standard                    none          90             95
3      male  free/reduced                    none          47             57
4      male      standard                    none          76             78
..      ...           ...                     ...         ...            ...
995  female      standard               completed          88             99
996    male  free/reduced                    none          62             55
997  female  free/reduced               completed          59             71
998  female      standard               completed          68             78
999  female  free/reduced                    none          77             86

     writing_score
0               74
1               88
2               93
3               44
4               75
..             ...
995             95
996             55
997             65
998             77
999             86

[1000 rows x 6 columns]

In [ ]:
print(StuPerfDF.info())
print(StuPerfDF.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   gender                   1000 non-null   object
 1   lunch                    1000 non-null   object
 2   test_preparation_course  1000 non-null   object
 3   math_score               1000 non-null   int64
 4   reading_score            1000 non-null   int64
 5   writing_score            1000 non-null   int64
dtypes: int64(3), object(3)
memory usage: 47.0+ KB
None
       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
print(StuPerfDF.columns)

Index(['gender', 'lunch', 'test_preparation_course', 'math_score',
       'reading_score', 'writing_score'],
      dtype='object')

In [ ]:
print(StuPerfDF['math_score'].mean())
print(StuPerfDF['writing_score'].mean())
print(StuPerfDF['reading_score'].mean())

66.089
68.054
69.169

In [ ]:
print(StuPerfDF['math_score'][StuPerfDF['lunch'] == 'standard'].mean())
print(StuPerfDF['math_score'][StuPerfDF['lunch'] != 'standard'].mean())

70.03410852713178
58.92112676056338

In [ ]:
StuPerfDF[['math_score','reading_score','writing_score']][StuPerfDF['test_preparation_course'] == 'none'].mean()

math_score       64.077882
reading_score    66.534268
writing_score    64.504673
dtype: float64

In [ ]:
StuPerfDF[['math_score','reading_score','writing_score']][StuPerfDF['test_preparation_course'] == 'completed'].mean()

math_score       69.695531
reading_score    73.893855
writing_score    74.418994
dtype: float64

In [6]:
empData = pd.read_csv('employees.csv')
print(empData)

      Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   30   Chicago   80000
2  Charlie   28    Boston   75000

In [19]:
empData[(empData['Age'] < 30) & (empData['Salary'] > 79000)]

Empty DataFrame
Columns: [Name, Age, City, Salary]
Index: []

In [22]:
empData[(empData['Age'] > 30) | (empData['Salary'] > 79000)]

  Name  Age     City  Salary
1  Bob   30  Chicago   80000

In [26]:
empData[(empData['City'] == 'Boston' ) | (empData['Salary'] < 5000 )]

      Name  Age    City  Salary
2  Charlie   28  Boston   75000

In [36]:
empData[(empData['Age'] > 23 ) & (empData['Age'] <= 25 )]

    Name  Age      City  Salary
0  Alice   25  New York   70000

In [37]:
empData[empData['Age'].between(23,27)]

    Name  Age      City  Salary
0  Alice   25  New York   70000

In [47]:
empData[empData['Salary'].between(80000,95000)]

  Name  Age     City  Salary
1  Bob   30  Chicago   80000

In [60]:
empData[empData['Name'].str.contains('c',case = False)]

      Name  Age      City  Salary
0    Alice   25  New York   70000
2  Charlie   28    Boston   75000

In [61]:
empData[empData['Name'].str.startswith('B')]

  Name  Age     City  Salary
1  Bob   30  Chicago   80000

In [81]:
empData.loc[len(empData)] = ['Abdullah',None,'Muscat',12000]

<ipython-input-81-686d16328d6a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empData.loc[len(empData)] = ['Abdullah',None,'Muscat',12000]

In [80]:
empData = empData.iloc[:-2]

In [82]:
empData

       Name   Age      City  Salary
0     Alice    25  New York   70000
1       Bob    30   Chicago   80000
2   Charlie    28    Boston   75000
3  Abdullah  None    Muscat   12000

In [93]:
empData.isnull()

    Name    Age   City  Salary
0  False  False  False   False
1  False  False  False   False
2  False  False  False   False
3  False   True  False   False

In [91]:
empData[empData.isnull().any(axis=1)]

       Name   Age    City  Salary
3  Abdullah  None  Muscat   12000

In [96]:
mask = empData['City'] == 'Muscat'
empData[mask]

       Name   Age    City  Salary
3  Abdullah  None  Muscat   12000

In [107]:
empData['Salary'].mask(empData['Salary'] >  15000,0)

0        0
1        0
2        0
3    12000
Name: Salary, dtype: int64

In [110]:
empData.drop(columns=['Age'])

       Name      City  Salary
0     Alice  New York   70000
1       Bob   Chicago   80000
2   Charlie    Boston   75000
3  Abdullah    Muscat   12000

In [112]:
empData['Bonus'] = empData['Salary']*0.1

<ipython-input-112-9b7226b1221f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empData['Bonus'] = empData['Salary']*0.1

In [113]:
empData

       Name   Age      City  Salary   Bonus
0     Alice    25  New York   70000  7000.0
1       Bob    30   Chicago   80000  8000.0
2   Charlie    28    Boston   75000  7500.0
3  Abdullah  None    Muscat   12000  1200.0

In [114]:
empData['Age'] = empData['Age'] + 1

<ipython-input-114-a94ff5bd6ab1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  empData['Age'] = empData['Age'] + 1

In [116]:
empData

       Name  Age      City  Salary   Bonus
0     Alice   26  New York   70000  7000.0
1       Bob   31   Chicago   80000  8000.0
2   Charlie   29    Boston   75000  7500.0
3  Abdullah  NaN    Muscat   12000  1200.0

In [118]:
empData.rename(columns={'Salary':'Income'})

       Name  Age      City  Income   Bonus
0     Alice   26  New York   70000  7000.0
1       Bob   31   Chicago   80000  8000.0
2   Charlie   29    Boston   75000  7500.0
3  Abdullah  NaN    Muscat   12000  1200.0

In [119]:
empData.drop('Bonus',axis=1)

       Name  Age      City  Salary
0     Alice   26  New York   70000
1       Bob   31   Chicago   80000
2   Charlie   29    Boston   75000
3  Abdullah  NaN    Muscat   12000

In [121]:
empData

       Name  Age      City  Salary   Bonus
0     Alice   26  New York   70000  7000.0
1       Bob   31   Chicago   80000  8000.0
2   Charlie   29    Boston   75000  7500.0
3  Abdullah  NaN    Muscat   12000  1200.0

In [124]:
empData.fillna(0)

<ipython-input-124-c2a14f9ed569>:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  empData.fillna(0)

       Name  Age      City  Salary   Bonus
0     Alice   26  New York   70000  7000.0
1       Bob   31   Chicago   80000  8000.0
2   Charlie   29    Boston   75000  7500.0
3  Abdullah    0    Muscat   12000  1200.0

In [127]:
empData_clean = empData.fillna(0)
empData_clean

<ipython-input-127-850c5e72c48d>:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  empData_clean = empData.fillna(0)

       Name  Age      City  Salary   Bonus
0     Alice   26  New York   70000  7000.0
1       Bob   31   Chicago   80000  8000.0
2   Charlie   29    Boston   75000  7500.0
3  Abdullah    0    Muscat   12000  1200.0

In [129]:
empData_clean.sort_values('Name')

       Name  Age      City  Salary   Bonus
3  Abdullah    0    Muscat   12000  1200.0
0     Alice   26  New York   70000  7000.0
1       Bob   31   Chicago   80000  8000.0
2   Charlie   29    Boston   75000  7500.0

In [132]:
empData_clean.sort_values('Salary',ascending=False)

       Name  Age      City  Salary   Bonus
1       Bob   31   Chicago   80000  8000.0
2   Charlie   29    Boston   75000  7500.0
0     Alice   26  New York   70000  7000.0
3  Abdullah    0    Muscat   12000  1200.0

In [139]:
empData.groupby('City')['Salary'].mean()

City
Boston      75000.0
Chicago     80000.0
Muscat      12000.0
New York    70000.0
Name: Salary, dtype: float64

In [143]:
empData.groupby('City')['Salary'].max()

City
Boston      75000
Chicago     80000
Muscat      12000
New York    70000
Name: Salary, dtype: int64

In [145]:
empData['City'].value_counts()

City
New York    1
Chicago     1
Boston      1
Muscat      1
Name: count, dtype: int64

In [147]:
empData.to_csv('Indexed_updated_Employees.csv',index=True)